### ISSUE TITLE
大佬为什么连接不上

### ISSUE THREAD

**Issue by Boosneo** [Frank17/ChatOnline#8]
chat-websocket.js:161 Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://0:0:0:0:0:0:0:1:8888/chat-online-maven/chatroom/chat/root' is invalid.
    at initConnection (http://localhost:8888/asserts/js/chat-websocket.js:161:16)
    at HTMLDocument.<anonymous> (http://localhost:8888/asserts/js/chat-websocket.js:56:2)
    at j (http://localhost:8888/asserts/js/jquery-2.1.4.min.js:2:26925)
    at Object.fireWith [as resolveWith] (http://localhost:8888/asserts/js/jquery-2.1.4.min.js:2:27738)
    at Function.ready (http://localhost:8888/asserts/js/jquery-2.1.4.min.js:2:29532)
    at HTMLDocument.I (http://localhost:8888/asserts/js/jquery-2.1.4.min.js:2:29723)

**Comment by zipzou** [comment]
`ws://0:0:0:0:0:0:0:1:8888` IP及端口请根据实际情况修改 @Boosneo

**Comment by Boosneo** [comment]
chat-websocket.js:161 WebSocket connection to 'ws://127.0.0.1:8888/chat-online-maven/chatroom/chat/root' failed: Error during WebSocket handshake: Unexpected response code: 404




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年5月27日(星期三) 上午9:36
收件人: "Frank17/ChatOnline"<ChatOnline@noreply.github.com&gt;; 
抄送: "无雨"<371008985@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Frank17/ChatOnline] 大佬为什么连接不上 (#8)





 
ws://0:0:0:0:0:0:0:1:8888 IP及端口请根据实际情况修改 @Boosneo
